apiVersion: v1
kind: Secret
metadata:
  name: __NAMESPACE_NAME__-secret
  namespace: __NAMESPACE_NAME__
type: Opaque
stringData:
  TX_BACKEND_TOKEN: __TX_BACKEND_TOKEN__
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
